export declare enum E_ASN1_TYPES {
    EOC = 0,
    BOOLEAN = 1,
    INTEGER = 2,
    BIT_STRING = 3,
    OCTET_STRING = 4,
    NULL = 5,
    OID = 6,
    OBJECT_DESCRIPTOR = 7,
    EXTERNAL = 8,
    REAL = 9,
    ENUMERATION = 10,
    PDV = 11,
    UTF8_STRING = 12,
    RELATIVE_OID = 13,
    SEQUENCE = 16,
    SET = 17,
    NUMERIC_STRING = 18,
    PRINTABLE_STRING = 19,
    T61_STRING = 20,
    VIDEO_TEXT_STRING = 21,
    IA5_STRING = 22,
    UTC_TIME = 23,
    GENERALIZED_TIME = 24,
    GRAPHIC_STRING = 25,
    VISIBLE_STRING = 26,
    GENERAL_STRING = 28,
    UNIVERSAL_STRING = 29,
    CHARATER_STRING = 30,
    BMP_STRING = 31,
    CONSTRUCTOR = 32,
    CONTEXT = 128
}
export type BER_ASN1_TYPES = {
    [key: string]: E_ASN1_TYPES;
};
export declare const BER_ASN1_TYPES: BER_ASN1_TYPES;
