"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BER_ASN1_TYPES = exports.E_ASN1_TYPES = void 0;
var E_ASN1_TYPES;
(function (E_ASN1_TYPES) {
    E_ASN1_TYPES[E_ASN1_TYPES["EOC"] = 0] = "EOC";
    E_ASN1_TYPES[E_ASN1_TYPES["BOOLEAN"] = 1] = "BOOLEAN";
    E_ASN1_TYPES[E_ASN1_TYPES["INTEGER"] = 2] = "INTEGER";
    E_ASN1_TYPES[E_ASN1_TYPES["BIT_STRING"] = 3] = "BIT_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["OCTET_STRING"] = 4] = "OCTET_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["NULL"] = 5] = "NULL";
    E_ASN1_TYPES[E_ASN1_TYPES["OID"] = 6] = "OID";
    E_ASN1_TYPES[E_ASN1_TYPES["OBJECT_DESCRIPTOR"] = 7] = "OBJECT_DESCRIPTOR";
    E_ASN1_TYPES[E_ASN1_TYPES["EXTERNAL"] = 8] = "EXTERNAL";
    E_ASN1_TYPES[E_ASN1_TYPES["REAL"] = 9] = "REAL";
    E_ASN1_TYPES[E_ASN1_TYPES["ENUMERATION"] = 10] = "ENUMERATION";
    E_ASN1_TYPES[E_ASN1_TYPES["PDV"] = 11] = "PDV";
    E_ASN1_TYPES[E_ASN1_TYPES["UTF8_STRING"] = 12] = "UTF8_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["RELATIVE_OID"] = 13] = "RELATIVE_OID";
    E_ASN1_TYPES[E_ASN1_TYPES["SEQUENCE"] = 16] = "SEQUENCE";
    E_ASN1_TYPES[E_ASN1_TYPES["SET"] = 17] = "SET";
    E_ASN1_TYPES[E_ASN1_TYPES["NUMERIC_STRING"] = 18] = "NUMERIC_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["PRINTABLE_STRING"] = 19] = "PRINTABLE_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["T61_STRING"] = 20] = "T61_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["VIDEO_TEXT_STRING"] = 21] = "VIDEO_TEXT_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["IA5_STRING"] = 22] = "IA5_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["UTC_TIME"] = 23] = "UTC_TIME";
    E_ASN1_TYPES[E_ASN1_TYPES["GENERALIZED_TIME"] = 24] = "GENERALIZED_TIME";
    E_ASN1_TYPES[E_ASN1_TYPES["GRAPHIC_STRING"] = 25] = "GRAPHIC_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["VISIBLE_STRING"] = 26] = "VISIBLE_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["GENERAL_STRING"] = 28] = "GENERAL_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["UNIVERSAL_STRING"] = 29] = "UNIVERSAL_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["CHARATER_STRING"] = 30] = "CHARATER_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["BMP_STRING"] = 31] = "BMP_STRING";
    E_ASN1_TYPES[E_ASN1_TYPES["CONSTRUCTOR"] = 32] = "CONSTRUCTOR";
    E_ASN1_TYPES[E_ASN1_TYPES["CONTEXT"] = 128] = "CONTEXT";
})(E_ASN1_TYPES = exports.E_ASN1_TYPES || (exports.E_ASN1_TYPES = {}));
exports.BER_ASN1_TYPES = {
    EOC: 0,
    Boolean: 1,
    Integer: 2,
    BitString: 3,
    OctetString: 4,
    Null: 5,
    OID: 6,
    ObjectDescriptor: 7,
    External: 8,
    Real: 9,
    Enumeration: 10,
    PDV: 11,
    Utf8String: 12,
    RelativeOID: 13,
    Sequence: 16,
    Set: 17,
    NumericString: 18,
    PrintableString: 19,
    T61String: 20,
    VideotexString: 21,
    IA5String: 22,
    UTCTime: 23,
    GeneralizedTime: 24,
    GraphicString: 25,
    VisibleString: 26,
    GeneralString: 28,
    UniversalString: 29,
    CharacterString: 30,
    BMPString: 31,
    Constructor: 32,
    Context: 128,
};
